# sets maximal velocity and acceleration values along the trajectory
dynamic_params: {
  max_v: 6.0,
  max_a: 3
}
 
waypoints: {
  vertices: [   
    #{ position: [ -38.0,  10.0,   6.5] }, # Initial Pose
    { position: [ -50.0,   0.0,  10.0], velocity: [ 0.0, 0.0, 0.0] }, # First light 
    { position: [ -70.0, -20.0,  10.0] }, # Avoid Tree
    { position: [ -85.0, -15.0,  10.0] }, 
    { position: [-105.0, -10.0,  10.0] }, # WP1 towards entrance
    { position: [-120.0, -10.0,  10.0] },  
    { position: [-150.0, -10.0,  10.0] }, # WP2 towards entrance
    { position: [-175.0, -10.0,  10.0] }, 
    { position: [-200.0, -5.0,  12.0] }, # WP3 towards entrance  
    { position: [-240.0, -5.0,  12.0] }, 
    { position: [-280.0, -5.0,  12.0] }, 
  ]
}
 
